repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/psf/black
    rev: 24.1.1
    hooks:
      - id: black

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort

  - repo: local
    hooks:
      - id: pip-audit
        name: pip-audit
        entry: pip-audit
        args: []
        language: system
        pass_filenames: false
        types: [python] # Opcional: se você quiser que isso seja executado apenas quando arquivos Python forem alterados..