name: CI Workflow

on: [pull_request]

jobs:
  start:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Intall poetry
        run: |
          curl -sS https://install.python-poetry.org | python3 -

      - name: Run pytest
        run: poetry run pytest

